### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by jlaws** [thowi/feedly-filter-chrome-extension#2]
Feedly updated their site so this is no longer working.  Are you planning on doing a fix?

**Comment by thowi** [comment]
Hey Joe,

Thanks for the report!
I'm on vacation for another week, but will fix it soon afterward.

Cheers

**Comment by jlaws** [comment]
Back home yet? :)

**Comment by thowi** [comment]
Hey, this is fixed in version 1.0.1 which I just uploaded to the Chrome Web Store.
Happy filtering!
